# Generated by Django 5.2.5 on 2025-09-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_categories_alter_listing_image_url_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
